//
// Created by yoshi on 24/02/21.
//


#ifndef COLLABORATIVEAUTHENTICATIONAPPLICATION_COMMON_H
#define COLLABORATIVEAUTHENTICATIONAPPLICATION_COMMON_H
#define SIZE       8
#define CONSTANT   977
#define MAX        0xFFFFFFFF
#define WORD_SIZE  32
#endif //COLLABORATIVEAUTHENTICATIONAPPLICATION_COMMON_H
